services:
  ffmpeg-compiler:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_ID: ${UID:-1000}
        GROUP_ID: ${GID:-1000}
    #user: "${UID:-1000}:${GID:-1000}"
    container_name: ffmpeg-build-container
    #cgroup: host
    volumes:
      #- /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /usr/local/cuda:/usr/local/cuda:ro
      # Mapear diretórios locais para os diretórios build e local do container
      - ./:/ffmpeg-build/:ro              # Código e scripts (só leitura)
      - ./build:/ffmpeg-build/build       # Build artifacts (escrita)
      - ./local:/ffmpeg-build/local       # Binários finais (escrita)local
    environment:
      - TZ=America/Maceio
    # Manter o container rodando após a compilação para inspeção
    tty: true
    stdin_open: true
