name: compile libs

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  schedule:
    - cron: 0 21 * * 0
  workflow_dispatch:
    inputs:
      name:
        description: 'Compile all'
        default: 'World'
        required: true

jobs:
  build_on_debian_11:
    name: build on ubuntu
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: install dependencies
      run: |
        sudo apt update
        sudo apt install -y autoconf automake build-essential libtool pkg-config texi2html yasm cmake curl mercurial git wget gperf ninja-build cargo python3-pip
        sudo python -m pip install --upgrade --user meson
    - name: install cargo-c
      run: |
        sudo rustup default stable
        sudo rustup update
        sudo cargo install cargo-c
