name: compile libs

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  schedule:
    - cron: 0 21 * * 0
  workflow_dispatch:
    inputs:
      name:
        description: 'Compile all'
        default: 'World'
        required: true

jobs:
  build_on_debian_11:
    name: build on ubuntu
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: install dependencies
      run: |
        sudo apt update
        sudo apt install -y texi2html yasm cmake gperf ninja-build
        sudo python -m pip install --upgrade --user meson
    - name: install rust
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        source $HOME/.cargo/env
        rustup default nightly
        rustup update
        cargo install cargo-c
    - name: compile libs
      run: |
        cat <<EOF > build_config.txt
        --enable-decklink
        --enable-libklvanc
        --disable-ffplay
        --disable-sdl2
        --enable-fontconfig
        --enable-libaom
        --enable-libass
        --enable-libbluray
        --enable-libfdk-aac
        --enable-libfribidi
        --enable-libfreetype
        --enable-libmp3lame
        --enable-libopus
        --enable-libsoxr
        --enable-libsrt
        --enable-libtwolame
        --enable-libvpx
        --enable-libx264
        --enable-libx265
        --enable-libzimg
        --enable-libzmq
        --enable-nonfree
        --enable-opencl
        --enable-opengl
        --enable-openssl
        --enable-libsvtav1
        --enable-librav1e
        --enable-libdav1d
        EOF

        ./compile-ffmpeg.sh --libs-only=y
